[package]
name = "ra1n-oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9"
rusty_libimobiledevice="0.1.7"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
